<craft> 
    <parameter name="width" type="int" default="5"/>
    <parameter name="length" type="int" default="15"/>
    <parameter name="height" type="int" default="1"/>
    <script>

        function main() {
            if (params.width < 2)
                params.width = 2;

            if (params.length < 2)
                params.length = 2;

            if (params.width/params.length < 0.2)
                params.width = 0.2 * params.length;
            
            return difference(
                body(),
                teeth().translate([0, params.length / 12, 0])
            ).scale(2);

            // comb components
            function body() {
                var combMain, combDome;

                // parts
                combMain = cube({size: [params.width - 0.5, params.length, params.height]});
                combDome = cylinder({
                    r: params.length / 2, 
                    h: params.height
                });
                
                // transformations
                combMain = translate([0.1, 0, 0], combMain);
                combDome = translate([0.2, params.length / 2, 0], combDome);
                combDome = scale([0.3, 1, 1], combDome); 
                
                return union(combMain, combDome);
            }

            function teeth() {
                var t;

                // parts
                t = cube({size: [params.width, 0.2, params.height]});
                
                // transformation
                for (var i = 0; i <= params.length*2; i++) {
                    t = union(t, t.translate([0, 0.4, 0]));
                }
                
                return t;
            }
        }

    </script>
</craft>